
import { Vocab, Kanji, Grammar, Example } from '@/types/dictionary';

export const mockVocabData: Vocab[] = [
  {
    id: 'v1',
    kanji: '食べる',
    kana: 'たべる',
    meaningVi: 'ăn',
    meaningEn: 'to eat',
    jlpt: 'N5',
    pos: 'verb',
    readingFurigana: '食[た]べる',
    pitch: '2',
  },
  {
    id: 'v2',
    kanji: '早い',
    kana: 'はやい',
    meaningVi: 'nhanh, sớm',
    meaningEn: 'fast, early',
    jlpt: 'N5',
    pos: 'adjective',
    readingFurigana: '早[はや]い',
    pitch: '0',
  },
  {
    id: 'v3',
    kanji: '勉強',
    kana: 'べんきょう',
    meaningVi: 'học tập',
    meaningEn: 'study',
    jlpt: 'N5',
    pos: 'noun',
    readingFurigana: '勉[べん]強[きょう]',
    pitch: '0',
  },
  {
    id: 'v4',
    kanji: '学校',
    kana: 'がっこう',
    meaningVi: 'trường học',
    meaningEn: 'school',
    jlpt: 'N5',
    pos: 'noun',
    readingFurigana: '学[がっ]校[こう]',
    pitch: '0',
  },
  {
    id: 'v5',
    kanji: '先生',
    kana: 'せんせい',
    meaningVi: 'giáo viên',
    meaningEn: 'teacher',
    jlpt: 'N5',
    pos: 'noun',
    readingFurigana: '先[せん]生[せい]',
    pitch: '3',
  },
  {
    id: 'v6',
    kanji: '本',
    kana: 'ほん',
    meaningVi: 'sách',
    meaningEn: 'book',
    jlpt: 'N5',
    pos: 'noun',
    readingFurigana: '本[ほん]',
    pitch: '1',
  },
  {
    id: 'v7',
    kanji: '見る',
    kana: 'みる',
    meaningVi: 'nhìn, xem',
    meaningEn: 'to see, to watch',
    jlpt: 'N5',
    pos: 'verb',
    readingFurigana: '見[み]る',
    pitch: '0',
  },
  {
    id: 'v8',
    kanji: '行く',
    kana: 'いく',
    meaningVi: 'đi',
    meaningEn: 'to go',
    jlpt: 'N5',
    pos: 'verb',
    readingFurigana: '行[い]く',
    pitch: '0',
  },
  {
    id: 'v9',
    kanji: '橋',
    kana: 'はし',
    meaningVi: 'cầu',
    meaningEn: 'bridge',
    jlpt: 'N5',
    pos: 'noun',
    readingFurigana: '橋[はし]',
    pitch: '0',
  },
  {
    id: 'v10',
    kanji: '箸',
    kana: 'はし',
    meaningVi: 'đũa',
    meaningEn: 'chopsticks',
    jlpt: 'N5',
    pos: 'noun',
    readingFurigana: '箸[はし]',
    pitch: '1',
  },
  {
    id: 'v11',
    kanji: '心',
    kana: 'こころ',
    meaningVi: 'trái tim, tâm hồn',
    meaningEn: 'heart, mind',
    jlpt: 'N4',
    pos: 'noun',
    readingFurigana: '心[こころ]',
    pitch: '3',
  },
];

export const mockKanjiData: Kanji[] = [
  {
    id: 'k1',
    char: '食',
    onyomi: 'ショク',
    kunyomi: 'た.べる',
    meaningVi: 'ăn',
    meaningEn: 'eat, food',
    jlpt: 'N5',
    radical: '食',
    strokeCount: 9,
  },
  {
    id: 'k2',
    char: '早',
    onyomi: 'ソウ、サッ',
    kunyomi: 'はや.い',
    meaningVi: 'sớm, nhanh',
    meaningEn: 'early, fast',
    jlpt: 'N5',
    radical: '日',
    strokeCount: 6,
  },
  {
    id: 'k3',
    char: '学',
    onyomi: 'ガク',
    kunyomi: 'まな.ぶ',
    meaningVi: 'học',
    meaningEn: 'study, learning',
    jlpt: 'N5',
    radical: '子',
    strokeCount: 8,
  },
  {
    id: 'k4',
    char: '校',
    onyomi: 'コウ',
    kunyomi: '',
    meaningVi: 'trường',
    meaningEn: 'school',
    jlpt: 'N5',
    radical: '木',
    strokeCount: 10,
  },
  {
    id: 'k5',
    char: '本',
    onyomi: 'ホン',
    kunyomi: 'もと',
    meaningVi: 'sách, gốc',
    meaningEn: 'book, origin',
    jlpt: 'N5',
    radical: '木',
    strokeCount: 5,
  },
];

export const mockGrammarData: Grammar[] = [
  {
    id: 'g1',
    pattern: '〜は〜です',
    jlpt: 'N5',
    descVi: 'Mẫu câu cơ bản để giới thiệu hoặc mô tả',
    descEn: 'Basic sentence pattern for introduction or description',
    structure: '[Danh từ] は [Danh từ/Tính từ] です',
  },
  {
    id: 'g2',
    pattern: '〜ます',
    jlpt: 'N5',
    descVi: 'Thể lịch sự của động từ',
    descEn: 'Polite form of verbs',
    structure: '[Động từ] ます',
  },
  {
    id: 'g3',
    pattern: '〜ません',
    jlpt: 'N5',
    descVi: 'Thể phủ định lịch sự của động từ',
    descEn: 'Polite negative form of verbs',
    structure: '[Động từ] ません',
  },
  {
    id: 'g4',
    pattern: '〜ました',
    jlpt: 'N5',
    descVi: 'Thể quá khứ lịch sự của động từ',
    descEn: 'Polite past form of verbs',
    structure: '[Động từ] ました',
  },
];

export const mockExamples: Example[] = [
  {
    id: 'e1',
    jp: 'ご飯を食べます。',
    vi: 'Tôi ăn cơm.',
    en: 'I eat rice.',
    vocabId: 'v1',
  },
  {
    id: 'e2',
    jp: '朝早く起きます。',
    vi: 'Tôi dậy sớm vào buổi sáng.',
    en: 'I wake up early in the morning.',
    vocabId: 'v2',
  },
  {
    id: 'e3',
    jp: '毎日勉強します。',
    vi: 'Tôi học mỗi ngày.',
    en: 'I study every day.',
    vocabId: 'v3',
  },
  {
    id: 'e4',
    jp: '学校に行きます。',
    vi: 'Tôi đi đến trường.',
    en: 'I go to school.',
    vocabId: 'v4',
  },
  {
    id: 'e5',
    jp: '先生は優しいです。',
    vi: 'Giáo viên thì tử tế.',
    en: 'The teacher is kind.',
    vocabId: 'v5',
  },
];

// Helper function to cache examples
export const cacheExample = async (example: Example) => {
  // This is a mock function for now
  // In a real app, this would save to SQLite
  console.log('Caching example:', example.id);
  return Promise.resolve();
};
